create table if not exists public.agents (
  id bigint generated by default as identity primary key,
  chain_id integer not null default 56,
  agent_id numeric not null,
  owner text,
  agent_uri text,
  name text,
  description text,
  image text,
  active_claimed boolean,
  health_status text,
  last_seen timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (chain_id, agent_id)
);

create table if not exists public.endpoints (
  id bigint generated by default as identity primary key,
  agent_pk bigint not null references public.agents(id) on delete cascade,
  name text,
  url text not null,
  protocol text,
  version text,
  last_check_at timestamptz,
  last_status text,
  latency_ms integer,
  unique (agent_pk, url)
);

create table if not exists public.health_checks (
  id bigint generated by default as identity primary key,
  endpoint_id bigint not null references public.endpoints(id) on delete cascade,
  checked_at timestamptz not null default now(),
  status text not null,
  latency_ms integer,
  http_code integer,
  error text
);

create index if not exists agents_health_status_idx on public.agents (health_status);
create index if not exists endpoints_agent_pk_idx on public.endpoints (agent_pk);
create index if not exists health_checks_endpoint_checked_idx on public.health_checks (endpoint_id, checked_at desc);

alter table public.agents enable row level security;
alter table public.endpoints enable row level security;
alter table public.health_checks enable row level security;

create policy "public can read agents" on public.agents for select using (true);
create policy "public can read endpoints" on public.endpoints for select using (true);
create policy "public can read health checks" on public.health_checks for select using (true);
