"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {CAPABILITIES,INTENTS} from "@/lib/discovery";

type Agent={id:number;agent_id:string;name:string|null;description:string|null;active_claimed:boolean|null;health_status:string|null;capabilities?:string[]|null};
const PAGE_SIZE=24;
const label=(s:string|null)=>s==="LIVE"?"LIVE":s==="DEAD"?"OFFLINE":s==="TIMEOUT"?"SLOW":"UNVERIFIED";
const initials=(n:string|null)=>(n||"Agent").split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();

export default function Discover(){
 const [agents,setAgents]=useState<Agent[]>([]),[q,setQ]=useState(""),[intent,setIntent]=useState(""),[capability,setCapability]=useState(""),[status,setStatus]=useState(""),[loading,setLoading]=useState(true);
 const [total,setTotal]=useState(0),[hasMore,setHasMore]=useState(false),[loadingMore,setLoadingMore]=useState(false);
 const chosen=INTENTS.find(i=>i.id===intent);
 function buildParams(offset:number){const p=new URLSearchParams({limit:String(PAGE_SIZE),offset:String(offset)});if(q)p.set("q",q);if(capability)p.set("capability",capability);if(status)p.set("status",status);if(chosen&&!q)p.set("q",chosen.query);return p}
 useEffect(()=>{const t=setTimeout(async()=>{setLoading(true);const r=await fetch(`/api/agents?${buildParams(0)}`);const d=await r.json();setAgents(d.agents||[]);setTotal(d.total??0);setHasMore(!!d.hasMore);setLoading(false)},200);return()=>clearTimeout(t)},[q,intent,capability,status]);
 async function loadMore(){setLoadingMore(true);const r=await fetch(`/api/agents?${buildParams(agents.length)}`);const d=await r.json();setAgents(prev=>[...prev,...(d.agents||[])]);setHasMore(!!d.hasMore);setLoadingMore(false)}
 const clear=()=>{setQ("");setIntent("");setCapability("");setStatus("")};
 return <div className="shell"><nav className="nav"><div className="container" style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><Link href="/" className="brand"><span className="brand-mark">A</span>AgentLens</Link><div style={{display:"flex",alignItems:"center",gap:22}}><Link href="/" className="nav-link">Explore</Link><Link href="/discover" className="nav-link nav-link-active">Discover</Link><span className="nav-note">Discovery · BNB Smart Chain</span></div></div></nav><main className="container"><section className="hero"><div className="eyebrow"><span className="eyebrow-dot"/>Intent-based discovery</div><h1>What do you need an agent to do?</h1><p>Start with a job, capability, or name. AgentLens narrows the field, then lets you inspect the evidence.</p><div className="search-wrap"><span className="search-icon">⌕</span><input className="search" value={q} onChange={e=>{setQ(e.target.value);setIntent("")}} placeholder="e.g. monitor my DeFi position, find a trading agent…"/></div><div className="intent-row"><span className="intent-label">Popular needs</span>{INTENTS.map(i=><button key={i.id} className={`intent-chip ${intent===i.id?"selected":""}`} onClick={()=>{setIntent(i.id);setQ("")}}>{i.label}</button>)}</div></section><section><div className="section-head"><div><h2>Refine your search</h2><span>{chosen?`Showing agents for "${chosen.label}"`:"Filter by capability and current availability."}</span></div>{(q||intent||capability||status)&&<button className="clear-filter" onClick={clear}>Clear all</button>}</div><div className="filter-bar"><div className="filter-group"><span>Capability</span>{CAPABILITIES.map(c=><button key={c.id} className={`filter-chip ${capability===c.id?"active":""}`} onClick={()=>setCapability(capability===c.id?"":c.id)}>{c.label}</button>)}</div><div className="filter-group"><span>Availability</span>{[["LIVE","Live now"],["TIMEOUT","Slow"],["DEAD","Offline"]].map(([v,l])=><button key={v} className={`filter-chip ${status===v?"active":""}`} onClick={()=>setStatus(status===v?"":v)}>{l}</button>)}</div></div><div className="section-head" style={{marginTop:28}}><div><h2>Matching agents</h2></div><span>{loading?"Searching…":`${total} found`}</span></div>{loading?<div className="grid">{[1,2,3,4,5,6].map(i=><div key={i} className="card" style={{opacity:.4}}/>)}</div>:agents.length===0?<div className="empty"><strong>No strong matches yet.</strong><span>Try a broader job description or remove a filter.</span><button onClick={clear}>Reset discovery</button></div>:<>
 <div className="grid">{agents.map(a=>{const id=a.agent_id.split(":").pop();const caps=a.capabilities||[];return <Link key={a.id} href={`/agents/${id}`} className="card"><div className="card-top"><div className="avatar">{initials(a.name)}</div><span className={`badge ${a.health_status==="LIVE"?"badge-live":"badge-neutral"}`}>{label(a.health_status)}</span></div><div className="card-title" style={{marginTop:16}}><h3>{a.name||"Unnamed agent"}</h3><div className="agent-id">ERC-8004 · Agent #{id}</div></div>{caps.length>0&&<div className="tag-list">{caps.slice(0,3).map(c=><span key={c} className="tag">{c}</span>)}{caps.length>3&&<span className="tag tag-more">+{caps.length-3}</span>}</div>}<p className="card-description">{a.description||"No description provided in the registration."}</p><div className="card-footer"><span>{a.active_claimed?"Active claimed":"Registration found"}</span><span className="card-link">Inspect evidence →</span></div></Link>})}</div>
 {hasMore&&<div style={{display:"flex",justifyContent:"center",paddingBottom:80}}><button className="clear-filter" onClick={loadMore} disabled={loadingMore}>{loadingMore?"Loading…":`Load more (${total-agents.length} remaining)`}</button></div>}
 </>}</section></main><footer className="footer"><div className="container footer-inner"><span><strong>AgentLens</strong> — the evidence layer for BNB AI agents.</span><span>Built for the Smart Money Era</span></div></footer></div>;
}